name: replay_trajectory_classification
channels:
- defaults
- conda-forge
- edeno
dependencies:
- numpy
- scipy
- pandas
- numba
- scikit-learn
- scikit-image
- joblib
- seaborn
- xarray
- dask
- regularized_glm
- tqdm
- flake8
- jupyter
- jupyterlab
- nb_conda
- setuptools
- ripple_detection
- loren_frank_data_processing
- track_linearization
- pip
- pip:
  - 'black[jupyter]'
