name: replay_trajectory_classification
channels:
- conda-forge
- franklab
- edeno
- defaults
dependencies:
- numpy
- scipy
- pandas
- numba
- scikit-learn
- scikit-image
- joblib
- seaborn
- xarray
- dask
- distributed
- tqdm
- flake8
- jupyter
- jupyterlab
- setuptools