name: replay_trajectory_classification
channels:
- conda-forge
- franklab
- edeno
- defaults
dependencies:
- numpy
- scipy
- pandas
- numba
- scikit-learn
- joblib
- seaborn
- xarray
- dask
- distributed
- regularized_glm
- tqdm
- flake8
- jupyter
- jupyterlab
- setuptools
- ripple_detection
- loren_frank_data_processing
- track_linearization
- pip
- pip:
  - 'black[jupyter]'
