name: PR Test

on: push

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
    - name: Cancel Workflow Action
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.9'
        miniforge-version: latest
        use-mamba: true
        channels: conda-forge,franklab,edeno,defaults
        channel-priority: true
        activate-environment: replay_trajectory_classification
        environment-file: environment.yml
    - name: Install replay_trajectory_classification
      shell: bash -l {0}
      run: |
        pip install -e .
    - name: Test notebooks
      shell: bash -l {0}
      run: |
        jupyter nbconvert --to notebook --ExecutePreprocessor.kernel_name=python3 --execute notebooks/tutorial/01-Introduction_and_Data_Format.ipynb
        jupyter nbconvert --to notebook --ExecutePreprocessor.kernel_name=python3 --execute notebooks/tutorial/02-Decoding_with_Sorted_Spikes.ipynb
        jupyter nbconvert --to notebook --ExecutePreprocessor.kernel_name=python3 --execute notebooks/tutorial/03-Decoding_with_Clusterless_Spikes.ipynb
        jupyter nbconvert --to notebook --ExecutePreprocessor.kernel_name=python3 --execute notebooks/tutorial/04-Classifying_with_Sorted_Spikes.ipynb
        jupyter nbconvert --to notebook --ExecutePreprocessor.kernel_name=python3 --execute notebooks/tutorial/05-Classifying_with_Clusterless_Spikes.ipynb
